[package]
name = "kdc"
version = "0.1.0"
edition = "2024"
readme = "README.md"
license = "MIT/Apache-2.0"
homepage = "https://github.com/devolutions/sspi-rs"
repository = "https://github.com/devolutions/sspi-rs"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
description = "A minimal Rust implementation of the KDC (Key Distribution Center)"

[dependencies]
picky-asn1 = { version = "0.10", features = ["time_conversion"] }
picky-asn1-der = "0.5"
picky-asn1-x509 = "0.15"
picky-krb = "0.12"
tracing = { version = "0.1", default-features = false }
time = { version = "0.3", default-features = false }

thiserror = "2.0"
argon2 = { version = "0.5", features = ["std"] }

zeroize = { version = "1.8", features = ["zeroize_derive"] }

[lints]
workspace = true
