[package]
name = "dpapi"
version = "0.0.0"
edition = "2024"
readme = "README.md"
license = "MIT/Apache-2.0"
homepage = "https://github.com/devolutions/sspi-rs"
repository = "https://github.com/devolutions/sspi-rs"
authors = ["Devolutions Inc. <infos@devolutions.net>"]
description = "A Rust implementation of Windows DPAPI"
publish = false # not ready yet

[lib]
name = "dpapi"

[features]
tsssp = ["sspi/tsssp"]

[dependencies]
bitflags = "2.11"
byteorder = "1.5"
num-derive = "0.5"
num-traits = { version = "0.2", default-features = true }
uuid = { version = "1.23", default-features = false, features = ["std"] }
picky-asn1 = "0.10"
picky-asn1-der = "0.5"
picky-krb = "0.12"
picky-asn1-x509 = { version = "0.15", features = ["pkcs7"] }
sha1 = { version = "0.11", default-features = false }
sha2 = "0.11"
rand = "0.10"
rand_core = "0.10"
hmac = "0.13"
digest = "0.11"
tracing = { version = "0.1", default-features = true }
whoami = "2.1"

dpapi-core = { workspace = true, features = ["alloc"] }
dpapi-pdu.workspace = true
dpapi-transport.workspace = true
sspi = { path = "../..", version = "0.21" } # public

kbkdf = "=0.1.0-rc.1"
elliptic-curve = { version = "0.14.0", features = ["sec1", "std"] }
p521 = { version = "0.14", features = ["ecdh"] }
p256 = { version = "0.14", features = ["ecdh"] }
p384 = { version = "0.14", features = ["ecdh"] }
concat-kdf = { git = "https://github.com/RustCrypto/KDFs.git", rev = "f2f5c03" } # TODO: We need the new version, but it's not released yet.
typenum = "1.20"
aes-kw = "0.3"
aes-gcm = { version = "=0.11.1", features = ["getrandom"] }
url = "2.5"

thiserror = "2.0"
regex = "1.12"

getrandom = "0.4"

# Pin transitive dependencies
# TODO: Remove when stable versions will be released
pkcs1 = "=0.8.0-rc.4"
rsa = { version = "=0.10.0-rc.18", default-features = false }

[dev-dependencies]
paste = "1.0"

[lints]
workspace = true
