[package]
name = "dpapi-cli-client"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
xflags = "0.3"
dpapi = { path = "../dpapi" }
tracing-subscriber = { workspace = true, features = ["std", "fmt", "local-time", "env-filter"] }
