[package]
name = "dpapi-pdu"
version = "0.1.0"
edition = "2024"
publish = false # not ready yet

[features]
std = []
arbitrary = ["uuid/arbitrary", "bitflags/arbitrary", "dep:arbitrary", "std"]

[dependencies]
dpapi-core = { workspace = true, features = ["alloc"] }
uuid = { version = "1.23", default-features = false }
crypto-bigint = { version = "0.7", default-features = false, features = ["alloc"] }
bitflags = "2.11"
num-derive = "0.5"
num-traits = { version = "0.2", default-features = true }

thiserror = { version = "2.0", default-features = false }
arbitrary = {  version = "1", optional = true, features = ["derive"] }

[dev-dependencies]
paste = "1.0"

[lints]
workspace = true
