use super::scard_context::{
    SCardAccessStartedEventFn, SCardAddReaderToGroupAFn, SCardAddReaderToGroupWFn, SCardCancelFn,
    SCardEstablishContextFn, SCardForgetReaderAFn, SCardForgetReaderGroupAFn, SCardForgetReaderGroupWFn,
    SCardForgetReaderWFn, SCardFreeMemoryFn, SCardGetCardTypeProviderNameAFn, SCardGetCardTypeProviderNameWFn,
    SCardGetProviderIdAFn, SCardGetProviderIdWFn, SCardGetStatusChangeAFn, SCardGetStatusChangeWFn,
    SCardIntroduceCardTypeAFn, SCardIntroduceCardTypeWFn, SCardIntroduceReaderAFn, SCardIntroduceReaderGroupAFn,
    SCardIntroduceReaderGroupWFn, SCardIntroduceReaderWFn, SCardIsValidContextFn, SCardListCardsAFn, SCardListCardsWFn,
    SCardListInterfacesAFn, SCardListInterfacesWFn, SCardListReaderGroupsAFn, SCardListReaderGroupsWFn,
    SCardListReadersAFn, SCardListReadersWFn, SCardLocateCardsAFn, SCardLocateCardsByATRAFn, SCardLocateCardsByATRWFn,
    SCardLocateCardsWFn, SCardReleaseContextFn, SCardReleaseStartedEventFn, SCardRemoveReaderFromGroupAFn,
    SCardRemoveReaderFromGroupWFn, SCardSetCardTypeProviderNameAFn, SCardSetCardTypeProviderNameWFn,
};

#[repr(C)]
pub struct SCardApiFunctionTable {
    pub dw_version: u32,
    pub dw_flags: u32,

    SCardEstablishContext: SCardEstablishContextFn,
    SCardReleaseContext: SCardReleaseContextFn,
    SCardIsValidContext: SCardIsValidContextFn,
    SCardListReaderGroupsA: SCardListReaderGroupsAFn,
    SCardListReaderGroupsW: SCardListReaderGroupsWFn,
    SCardListReadersA: SCardListReadersAFn,
    SCardListReadersW: SCardListReadersWFn,
    SCardListCardsA: SCardListCardsAFn,
    SCardListCardsW: SCardListCardsWFn,
    SCardListInterfacesA: SCardListInterfacesAFn,
    SCardListInterfacesW: SCardListInterfacesWFn,
    SCardGetProviderIdA: SCardGetProviderIdAFn,
    SCardGetProviderIdW: SCardGetProviderIdWFn,
    SCardGetCardTypeProviderNameA: SCardGetCardTypeProviderNameAFn,
    SCardGetCardTypeProviderNameW: SCardGetCardTypeProviderNameWFn,
    SCardIntroduceReaderGroupA: SCardIntroduceReaderGroupAFn,
    SCardIntroduceReaderGroupW: SCardIntroduceReaderGroupWFn,
    SCardForgetReaderGroupA: SCardForgetReaderGroupAFn,
    SCardForgetReaderGroupW: SCardForgetReaderGroupWFn,
    SCardIntroduceReaderA: SCardIntroduceReaderAFn,
    SCardIntroduceReaderW: SCardIntroduceReaderWFn,
    SCardForgetReaderA: SCardForgetReaderAFn,
    SCardForgetReaderW: SCardForgetReaderWFn,
    SCardAddReaderToGroupA: SCardAddReaderToGroupAFn,
    SCardAddReaderToGroupW: SCardAddReaderToGroupWFn,
    SCardRemoveReaderFromGroupA: SCardRemoveReaderFromGroupAFn,
    SCardRemoveReaderFromGroupW: SCardRemoveReaderFromGroupWFn,
    SCardIntroduceCardTypeA: SCardIntroduceCardTypeAFn,
    SCardIntroduceCardTypeW: SCardIntroduceCardTypeWFn,
    SCardSetCardTypeProviderNameA: SCardSetCardTypeProviderNameAFn,
    SCardSetCardTypeProviderNameW: SCardSetCardTypeProviderNameWFn,
    SCardFreeMemory: SCardFreeMemoryFn,
    SCardAccessStartedEvent: SCardAccessStartedEventFn,
    SCardReleaseStartedEvent: SCardReleaseStartedEventFn,
    SCardLocateCardsA: SCardLocateCardsAFn,
    SCardLocateCardsW: SCardLocateCardsWFn,
    SCardLocateCardsByATRA: SCardLocateCardsByATRAFn,
    SCardLocateCardsByATRW: SCardLocateCardsByATRWFn,
    SCardGetStatusChangeA: SCardGetStatusChangeAFn,
    SCardGetStatusChangeW: SCardGetStatusChangeWFn,
    SCardCancel: SCardCancelFn,
}
